kind: Namespace               # Defines the type of resource as a Namespace
apiVersion: v1                # Specifies the API version for the resource
metadata:                     # Metadata provides details about the resource
  name: devopsmolvi-elasticsearch  # Unique name for the Namespace
